export const DB_ERROR = {
  OWNER_NOT_FOUND: 'OWNER_NOT_FOUND',
  DOG_NOT_FOUND: 'DOG_NOT_FOUND',
  OWNER_HAS_DOGS: 'OWNER_HAS_DOGS',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  INVALID_APPOINTMENT_DATE_TIME: 'INVALID_APPOINTMENT_DATE_TIME',
  INVALID_APPOINTMENT_DURATION: 'INVALID_APPOINTMENT_DURATION',
  INVALID_APPOINTMENT_PRICE: 'INVALID_APPOINTMENT_PRICE',
  INVALID_APPOINTMENT_STATUS: 'INVALID_APPOINTMENT_STATUS',
  INVALID_NOTE_SCOPE: 'INVALID_NOTE_SCOPE',
  TAG_DEFINITION_NOT_FOUND: 'TAG_DEFINITION_NOT_FOUND',
  INVALID_TAG_SCOPE: 'INVALID_TAG_SCOPE',
  INVALID_TAG_COLOR: 'INVALID_TAG_COLOR',
  TAG_LABEL_REQUIRED: 'TAG_LABEL_REQUIRED',
  TAG_SCOPES_REQUIRED: 'TAG_SCOPES_REQUIRED',
  TAG_TARGET_NOT_FOUND: 'TAG_TARGET_NOT_FOUND',
} as const

export type DatabaseErrorCode = (typeof DB_ERROR)[keyof typeof DB_ERROR]
