export const DB_ERROR = {
  OWNER_NOT_FOUND: 'OWNER_NOT_FOUND',
  DOG_NOT_FOUND: 'DOG_NOT_FOUND',
  OWNER_HAS_DOGS: 'OWNER_HAS_DOGS',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  INVALID_APPOINTMENT_DATE_TIME: 'INVALID_APPOINTMENT_DATE_TIME',
  INVALID_APPOINTMENT_DURATION: 'INVALID_APPOINTMENT_DURATION',
  INVALID_APPOINTMENT_PRICE: 'INVALID_APPOINTMENT_PRICE',
  INVALID_APPOINTMENT_TIP: 'INVALID_APPOINTMENT_TIP',
  INVALID_APPOINTMENT_STATUS: 'INVALID_APPOINTMENT_STATUS',
  INVALID_NOTE_SCOPE: 'INVALID_NOTE_SCOPE',
  TAG_DEFINITION_NOT_FOUND: 'TAG_DEFINITION_NOT_FOUND',
  INVALID_TAG_SCOPE: 'INVALID_TAG_SCOPE',
  INVALID_TAG_COLOR: 'INVALID_TAG_COLOR',
  TAG_LABEL_REQUIRED: 'TAG_LABEL_REQUIRED',
  TAG_SCOPES_REQUIRED: 'TAG_SCOPES_REQUIRED',
  TAG_TARGET_NOT_FOUND: 'TAG_TARGET_NOT_FOUND',
  PHOTO_SESSION_NOT_FOUND: 'PHOTO_SESSION_NOT_FOUND',
  INVALID_PHOTO_KIND: 'INVALID_PHOTO_KIND',
  PHOTO_PROCESSING_FAILED: 'PHOTO_PROCESSING_FAILED',
  PHOTO_STORAGE_QUOTA_EXCEEDED: 'PHOTO_STORAGE_QUOTA_EXCEEDED',
} as const

export type DatabaseErrorCode = (typeof DB_ERROR)[keyof typeof DB_ERROR]

export const PASSWORD_ERROR = {
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_CONFIRM_MISMATCH: 'PASSWORD_CONFIRM_MISMATCH',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  PASSWORD_ALREADY_SET: 'PASSWORD_ALREADY_SET',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  PASSWORD_CONFIG_INVALID: 'PASSWORD_CONFIG_INVALID',
} as const

export type PasswordErrorCode = (typeof PASSWORD_ERROR)[keyof typeof PASSWORD_ERROR]
