export const DB_ERROR = {
  OWNER_NOT_FOUND: 'OWNER_NOT_FOUND',
  DOG_NOT_FOUND: 'DOG_NOT_FOUND',
  OWNER_HAS_DOGS: 'OWNER_HAS_DOGS',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  INVALID_APPOINTMENT_DATE_TIME: 'INVALID_APPOINTMENT_DATE_TIME',
  INVALID_APPOINTMENT_DURATION: 'INVALID_APPOINTMENT_DURATION',
  INVALID_APPOINTMENT_PRICE: 'INVALID_APPOINTMENT_PRICE',
  INVALID_APPOINTMENT_STATUS: 'INVALID_APPOINTMENT_STATUS',
} as const

export type DatabaseErrorCode = (typeof DB_ERROR)[keyof typeof DB_ERROR]
